server:
  port: 8082
spring:
  jackson:
    default-property-inclusion: non_null
  application:
    name: applet-manage
eureka:
  instance:
  #注册名称
    instance-id: applet-manage
  #注册显示ip
    prefer-ip-address: true
info:
 app.name: applet-manage
 company.name: wangbin