server:
  port: 8084
#swagger:
#  enable: true
spring:
  application:
    name: applet-static
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://172.16.77.26:3306/applet?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  security:
   basic:
      enabled: false
   user:
     name: wb
     password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:7001/eureka/
  instance:
  #注册名称
    instance-id: applet-static
  #注册显示ip
    prefer-ip-address: true
info:
 app.name: applet-static
 company.name: wangbin
applet:
  imgSavePath: /home/testImage/
