package com.kute.appletcore.dao;

import com.kute.appletcore.entity.SysDataStructNodeAttribute;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SysDataStructNodeAttributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_data_struct_node_attribute
     *
     * @mbggenerated Tue Apr 10 16:09:16 CST 2018
     */
    int deleteByPrimaryKey(@Param("structCode") String structCode, @Param("nodeCode") String nodeCode, @Param("attributeCode") String attributeCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_data_struct_node_attribute
     *
     * @mbggenerated Tue Apr 10 16:09:16 CST 2018
     */
    int insert(SysDataStructNodeAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_data_struct_node_attribute
     *
     * @mbggenerated Tue Apr 10 16:09:16 CST 2018
     */
    SysDataStructNodeAttribute selectByPrimaryKey(@Param("structCode") String structCode, @Param("nodeCode") String nodeCode, @Param("attributeCode") String attributeCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_data_struct_node_attribute
     *
     * @mbggenerated Tue Apr 10 16:09:16 CST 2018
     */
    List<SysDataStructNodeAttribute> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_data_struct_node_attribute
     *
     * @mbggenerated Tue Apr 10 16:09:16 CST 2018
     */
    int updateByPrimaryKey(SysDataStructNodeAttribute record);


}