package com.kute.appletcore.dao;

import com.kute.appletcore.entity.SysDataStructNodeAttribute;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SysDataStructNodeAttributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_data_struct_node_attribute
     *
     * @mbggenerated Tue Apr 10 16:09:16 CST 2018
     */
    int deleteByPrimaryKey(@Param("struct_code") String struct_code, @Param("node_code") String node_code, @Param("attribute_code") String attribute_code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_data_struct_node_attribute
     *
     * @mbggenerated Tue Apr 10 16:09:16 CST 2018
     */
    int insert(SysDataStructNodeAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_data_struct_node_attribute
     *
     * @mbggenerated Tue Apr 10 16:09:16 CST 2018
     */
    SysDataStructNodeAttribute selectByPrimaryKey(@Param("struct_code") String struct_code, @Param("node_code") String node_code, @Param("attribute_code") String attribute_code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_data_struct_node_attribute
     *
     * @mbggenerated Tue Apr 10 16:09:16 CST 2018
     */
    List<SysDataStructNodeAttribute> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_data_struct_node_attribute
     *
     * @mbggenerated Tue Apr 10 16:09:16 CST 2018
     */
    int updateByPrimaryKey(SysDataStructNodeAttribute record);


}